# 1. Create jackknife resamples

In [1]:
import numpy as np
from astropy.stats import jackknife_resampling
from astropy.stats import jackknife_stats

In [2]:
data = np.array([1,2,3,4,5,6,7,8,9,0])

In [3]:
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [4]:
resamples = jackknife_resampling(data)

In [5]:
resamples

array([[2., 3., 4., 5., 6., 7., 8., 9., 0.],
       [1., 3., 4., 5., 6., 7., 8., 9., 0.],
       [1., 2., 4., 5., 6., 7., 8., 9., 0.],
       [1., 2., 3., 5., 6., 7., 8., 9., 0.],
       [1., 2., 3., 4., 6., 7., 8., 9., 0.],
       [1., 2., 3., 4., 5., 7., 8., 9., 0.],
       [1., 2., 3., 4., 5., 6., 8., 9., 0.],
       [1., 2., 3., 4., 5., 6., 7., 9., 0.],
       [1., 2., 3., 4., 5., 6., 7., 8., 0.],
       [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

# 2. Obtain Jackknife estimate for the mean, its bias, its standard error, and its 95% confidence interval

In [21]:
#mean of the resamples data
data_mean = np.mean(data)
data_mean

4.5

In [22]:
#standard devaition of the resamples data
data_sd = np.sqrt(np.var(data))
data_sd

2.8722813232690143

In [23]:
#estimated SE
est_se = data_sd/np.sqrt(10)

In [25]:
est_se

0.9082951062292475

In [26]:
est_ci_lower = 4.5 - 1.96*est_se

In [27]:
est_ci_upper = 4.5 + 1.96*est_se

In [32]:
est_ci = np.array([est_ci_lower, est_ci_upper])

In [33]:
est_ci

array([2.71974159, 6.28025841])

In [ ]:
test_statistic = np.mean
test_statistic

In [8]:
estimate, bias, stderr, conf_interval = jackknife_stats(
    data, test_statistic, 0.95)


4.5

In [10]:
estimate

4.5

In [11]:
bias

0.0

In [12]:
stderr

0.9574271077563383

In [13]:
conf_interval

array([2.62347735, 6.37652265])